### ISSUE TITLE
todo: update default vortex and proton versions

### ISSUE THREAD

**Issue by pikdum** [pikdum/steam-deck#32]
- [ ] verify that they work
- [ ] use them in install-vortex.sh
- [ ] if vortex is already installed, upgrade proton in post-install.sh

not too high of a priority, since current setup still works, but it's nice to keep up-to-date
